### ISSUE TITLE
Computed Object Keys 

### ISSUE THREAD

**Issue by GStudiosX2** [face-hh/bussin#42]
Computed Object Keys do not work for example: 
```
lit obj be {} rn
lit x be "e" rn
obj[x] = "hi"
```

Output if I `waffle(obj)`:
```{ x: 'hi' }```

Expected:
```{ 'e': 'hi' }```

And with numbers it should be ```{ 0: 'hi' }``` or ```{ '0': 'hi' }``` whichever is easier to implement 

Also if I do ```obj[x plusplus] = 'hi'``` where x is a number I get ```{ undefined: 'hi' }``` same if x was a string and you ```+ ""```

**Comment by GStudiosX2** [comment]
Maybe this isn't supported though but it will be pretty useful I think I don't really know what to call this lol

**Comment by face-hh** [comment]
This must be an issue with the way the runtime handles it, as by that point the code should've figured out it's an identifier of type Variable.

Since the function that computes and modified the values was made in a rush was a kind of hacky way to get around it, that's most likely the issue here.

As I've mentioned in previous issues, I lack the time necessary to go and fix all of these issues - so for now it will remain like that, unless there are some pull requests.

Thanks for taking the time to report this :^)

**Comment by GStudiosX2** [comment]
> This must be an issue with the way the runtime handles it, as by that point the code should've figured out it's an identifier of type Variable.
> 
> Since the function that computes and modified the values was made in a rush was a kind of hacky way to get around it, that's most likely the issue here.
> 
> As I've mentioned in previous issues, I lack the time necessary to go and fix all of these issues - so for now it will remain like that, unless there are some pull requests.
> 
> Thanks for taking the time to report this :^)

I see I might try and see if I can fix it myself

**Comment by face-hh** [comment]
To pinpoint (allegedly) the issue: https://github.com/face-hh/bussin/blob/main/src%2Fruntime%2Fenvironment.ts#L152

**Comment by Symmettry** [comment]
This is not completed; should probably not be closed

**Comment by Symmettry** [comment]
also worth mentioning doing obj[x] should not work when x is not a variable, but it is the only way to actually assign strings in objects.

doing obj["e"] will become { undefined: "val" }

i'll try to fix
